### ISSUE TITLE
Unpacked packages do not show in grid

### ISSUE THREAD

**Issue by charliez** [splittingred/PackMan#19]
When unpacking a transport package with sub-packages, the sub-packages install OK but they do not appear in the Package Management grid so they can be seen, upgraded, etc.

**Comment by splittingred** [comment]
This works for me. You using the latest PackMan?

**Comment by charliez** [comment]
Yes, I got the latest one installed.  I upgraded MODX and all the
extras before creating a new package, to unpack at the new install.
I will try again from scratch and report back.  

The interesting thing is that everything is installed OK and works fine.
Hopefully is not another host issue.
