### ISSUE TITLE
Subpackages (improvement ?)

### ISSUE THREAD

**Issue by rtripault** [splittingred/PackMan#2]
One awsome thing with PackMan is that you can pack other packages allowing you to make your toolset.
Anyway, once installed with your own package, you're not able to update each "subpackages" from the package manager (eg. if "myToolset" includes "getResources" it would be nice to allow me to update "getResources" without having to wait for a new "myToolset" build)

**Comment by splittingred** [comment]
Done, although if you uninstall the main package, it will uninstall all subpackages (expected).
