### ISSUE TITLE
Unable to move/delete unpackaged files/folders

### ISSUE THREAD

**Issue by charliez** [splittingred/PackMan#20]
The unpackaged files/folders/directories cannot be moved and or deleted which make the customization of the new install impossible.

**Comment by splittingred** [comment]
Not an issue with PackMan; more an issue with your PHP host.

**Comment by charliez** [comment]
Yes, sorry, I should have returned to delete or modified the issue...
The files were being created under the "nobody" owner instead of
under my user.
